apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapi
  minReadySeconds: 5
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 0
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: webapi
          image: varunsemwal/employee-api
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "100m"
          envFrom:
            - configMapRef:
                name: mongo-config
          env:
            - name: ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-config
                    key: ConnectionString
            - name: username
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password